beforescript:
  stage: build
  script:
    - echo " before script "
    - nix-shell -p blas liblapack gcc xorg.libXmu zlib cmake mesa_glu mesa icu python36 suitesparse tcl-8_5 tk-8_5 --run "echo \"nix-shell test\" "

build:
  stage: build
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - build/
  script:
    - mkdir -p ngsolve-build
    - cd ngsolve-build
    - git clone https://gitlab.gwdg.de/lehrenfeld/ngsolve.git --branch meshinterface --single-branch
    - cd ngsolve
    - git submodule sync
    - git submodule update --init --recursive
    - cd external_dependencies/netgen
    - git remote update        
    - git checkout $CI_COMMIT_SHA
    - cd ../..
    - mkdir -p build
    - cd build
    - nix-shell -p blas liblapack gcc gfortran gfortran.cc.lib xorg.libXmu zlib cmake mesa_glu mesa icu python36 suitesparse tcl-8_5 tk-8_5 --run "cmake -DCMAKE_INSTALL_PREFIX=`pwd`/inst -DCMAKE_BUILD_TYPE=RELEASE -DUSE_CCACHE=ON -DUSE_GUI=OFF -DTCL_INCLUDE_PATH=/usr/include/tcl8.5/ ../."
    - nix-shell -p blas liblapack gcc gfortran gfortran.cc.lib xorg.libXmu zlib cmake mesa_glu mesa icu python36 suitesparse tcl-8_5 tk-8_5 --run "make -j12"

cleanup:
  stage: deploy
  script:
    - echo " cleanup "
    - rm -rf `pwd`/inst
